Step 1/6 : FROM python:latest
 ---> 70aa8983ec5c
Step 2/6 : WORKDIR /code
 ---> Using cache
 ---> 84120fd40ea1
Step 3/6 : ADD requirements.txt requirements.txt
 ---> Using cache
 ---> 8017560f636c
Step 4/6 : RUN pip install -r requirements.txt
 ---> Using cache
 ---> 51890a9ac94c
Step 5/6 : COPY app.py app.py
 ---> 49581dbd1723
Step 6/6 : CMD ["python", "-u", "app.py"]
 ---> Running in 2ac9af9d0e6f
Removing intermediate container 2ac9af9d0e6f
 ---> 02510dab10ed

Successfully built 02510dab10ed
Successfully tagged docker_python_sql_tutorial_app:latest
Step 1/5 : FROM postgres:latest
 ---> 26c8bcd8b719
Step 2/5 : ENV POSTGRES_PASSWORD=secret
 ---> Using cache
 ---> 6c8f6f44c705
Step 3/5 : ENV POSTGRES_USER=username
 ---> Using cache
 ---> b10e0972f525
Step 4/5 : ENV POSTGRES_DB=database
 ---> Using cache
 ---> e9b1a4c9a6f4
Step 5/5 : COPY create_fixtures.sql /docker-entrypoint-initdb.d/create_fixtures.sql
 ---> 8e2d2f84d47e

Successfully built 8e2d2f84d47e
Successfully tagged docker_python_sql_tutorial_db:latest
Attaching to docker_python_sql_tutorial_app_1, docker_python_sql_tutorial_db_1
[36mapp_1  |[0m   File "/code/app.py", line 95
[36mapp_1  |[0m     salvarCandlesCadaDezMinutos(now):
[36mapp_1  |[0m                                      ^
[36mapp_1  |[0m SyntaxError: invalid syntax
[36mdocker_python_sql_tutorial_app_1 exited with code 1
[0m[33mdb_1   |[0m 
[33mdb_1   |[0m PostgreSQL Database directory appears to contain a database; Skipping initialization
[33mdb_1   |[0m 
[33mdb_1   |[0m 2021-05-07 17:49:35.505 UTC [1] LOG:  starting PostgreSQL 13.2 (Debian 13.2-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
[33mdb_1   |[0m 2021-05-07 17:49:35.513 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
[33mdb_1   |[0m 2021-05-07 17:49:35.514 UTC [1] LOG:  listening on IPv6 address "::", port 5432
[33mdb_1   |[0m 2021-05-07 17:49:35.520 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
[33mdb_1   |[0m 2021-05-07 17:49:35.542 UTC [25] LOG:  database system was shut down at 2021-05-07 16:17:12 UTC
[33mdb_1   |[0m 2021-05-07 17:49:35.691 UTC [1] LOG:  database system is ready to accept connections
Gracefully stopping... (press Ctrl+C again to force)
